INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Marcel Marreti Rosa', 'marcel.rosa@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Natan Novak', 'natan.novak@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Osmar Hideaki Nohara', 'osmar.nohara@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Paulo Maia', 'paulo.maia@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Pedro Cristovao Cussioli', 'pedro.cussioli@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Luiz Felipe Kataoka', 'luiz.kataoka@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Karen Moreno Spisso', 'karen.spisso@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Juliana Gomes Proenca', 'juliana.proenca@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Geovanna Carolina Favilla', 'geovanna.favilla@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Douglas Quintiliano Calixto', 'douglas.calixto@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Bruno Pavanelli Couto', 'bruno.couto@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Amanda Gaeta Parigini', 'amanda.parigini@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Adnam Marques Batista Junior', 'adnam.junior@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Alexandre Claret Albertos', 'alexandre.albertos@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Frederico Ribeiro Vilela Santeiro', 'frederico.santeiro@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Gabriel Biscaro Cavallari', 'gabriel.cavallari@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Gabriel Ferreira Monteiro', 'gabriel.monteiro@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Giorgia Soares Agostini', 'giorgia.agostini@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Lais Manesco Grigolon', 'lais.grigolon@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Leticia Consoline', 'leticia.consoline@myassist.com.br');
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL) VALUES ('Lucas Alexandre Soares', 'lucas.soares@myassist.com.br');
